### ISSUE TITLE
Failing tests in Pharo 7

### ISSUE THREAD

**Issue by guillep** [pharo-contributions/OSSubprocess#33]
The following two tests are failing in Pharo 7. Maybe due to the changes in \#atEnd?
```
OSSPipeTest
5cf32c_fe11
 ✗ #testIsAtEndOfFile (26ms)
TestFailure: Assertion failed
OSSPipeTest(TestAsserter)>>assert:
OSSPipeTest(TestAsserter)>>deny:
OSSPipeTest>>testIsAtEndOfFile ...deny: pipe reader atEnd
OSSPipeTest(TestCase)>>performTest
5cf32c_fe11
 ✗ #testIsAtEndOfFile (8ms)
TestFailure: Assertion failed
OSSPipeTest(TestAsserter)>>assert:
OSSPipeTest(TestAsserter)>>deny:
OSSPipeTest>>testIsAtEndOfFile ...deny: pipe reader atEnd
OSSPipeTest(TestCase)>>performTest
```

@akgrant43, can you confirm?

Maybe checking for atEnd of a pipe does not make sense and the test is just wrong.

**Comment by akgrant43** [comment]
Hi Guille,

#atEnd should work for pipes.  I have tested it, but obviously not every situation. :-)

I'm away from my PC, but will take a look as soon as I can.

Cheers,
Alistair

**Comment by guillep** [comment]
I don't quite understand if these assertions make sense...

```
pipe writer close.
self deny: (pipe reader atEndOfFile).
self deny: pipe atEndOfFile.
self deny: pipe reader atEnd. "==> This is the problematic line"
self assert: pipe atEnd. 
```

**Comment by akgrant43** [comment]
Hi Guille,

Your analysis and fix looks good to me.

The old code used the file position (which isn't valid for pipes), so #atEnd always returned true or false (I forget which, but based on the test, I assume it was false).  The new code uses feof(), and since the pipe has been closed, #atEnd should (and now does) return true.

Thanks,
Alistair

**Comment by akgrant43** [comment]
Actually, one quibble with the original code...

It doesn't make sense to test for an incorrect value.  It would be better to not test the value at all for Pharo 6 and earlier and state that #atEnd doesn't work for pipes.

But, like I said, it is a minor quibble.

Cheers,
Alistair

**Comment by guillep** [comment]
You convinced me :) I removed the assertion in Pharo 6. Waiting for the CI to finish

**Comment by akgrant43** [comment]
:-)

Thanks for the update!

Cheers,
Alistair
