### ISSUE TITLE
Often get waitpid() -1 in CI

### ISSUE THREAD

**Issue by guillep** [pharo-contributions/OSSubprocess#36]
We often get an error like the following in the CI, which is kind of annoying because it makes tests to fail randomly. Rerunning the job does fix it. So it may be a race condition?

```
Error: Error: waitpid(), code: -1, description: Unknown error -1
OSSUnixSystemAccessor(Object)>>error:
OSSUnixSystemAccessor>>strerror:message:
[ returnValue := self
	primitiveWaitpid: childPidInteger
	statusPointer: statusPointer
	options: WNOHANG.
returnValue = -1
	ifTrue: [ self strerror: returnValue message: 'waitpid()' ].
returnValue = 0
	ifTrue: [ ^ nil ].	"If waitpid() was invoked with WNOHANG set in options, it has at least one child process specified by pid for which status is not available, and status is not available for any process specified by pid, 0 is returned.
		That means...status is not available for childPidInteger..probably hasn't finished yet."
returnValue = childPidInteger
	ifTrue:
		[ "If wait() or waitpid() returns because the status of a child process is available, these functions shall return a value equal to the process ID of the child process for which status is reported.
			This means...status is available. It has finished. "
		answer := statusPointer platformLongAt: 1.
		^ answer ] ] in OSSUnixSystemAccessor>>waitpidNoHang:
BlockClosure>>ensure:
```

**Comment by guillep** [comment]
Well, we have found a solution for this. There are two main reasons for this issue:

1. There are potential race conditions in the callers of `waitpidNoHang:`. This method calls the function `waitpid` which in turn will wait for the finished child and *unregister* it from the child table in the OS process. This means that we cannot call twice `waitpid` for the same process, what would generate an error.
2. [`waitpid` man's page](man7.org/linux/man-pages/man2/waitpid.2.html) is ambiguous with respect of the usage of the `WNOHANG` option. Our finally hypothesis (confirmed by the code and the tests) is that `waitpid` ignores the first argument if `WNOHANG` is specified, and returns with ANY child process id. This means that, in combination with the previous issue, it may happen that calling `waitpid` for process X will unregister process Y, what will make fail a subsequent call to `waitpid` from Y.

**Comment by marianopeck** [comment]
Wow. Great catch @guillep. Excellent!!! 
But I have a doubt. It's likely the "parent" process is the VM process, right? Imagine I do use `WNOHANG`.  So each `OSSUnixSubprocess finishedChildProcesses` dictionary may be holding results of other `OSSUnixSubprocess` instances? (note that variable is instanceSide, not classSide).
 If that's true then that won't work I think
